pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./1-safety-precautions.html","Chapter 1   Safety &#62; Safety Precautions","Disregarding the specific instructions or precautions included in this manual may result in serious injury or death to the operators or surroundin...",""],
["./1000-hours-(4-months)-maintena.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals &#62; 1000 hours (4 Months) Maintenance","Unit Refer to Content of Maintenance Machine 3.1 Checking/Adjusting the Leveling of the Machine Chip Disposal/Cutting Fluid Supply Unit 10.4.2 Cle...",""],
["./1_1-operators-checks.html","Chapter 1   Safety &#62; Safety Precautions &#62; Operators Checks","Only qualified personnel who have adequate mechanical and technical knowledge are allowed to operate and maintain the machine.",""],
["./1_2-work-environment-checks.html","Chapter 1   Safety &#62; Safety Precautions &#62; Work Environment Checks","Make sure the machine and surrounding area are fully lighted.",""],
["./1_3-precautions-for-potential-.html","Chapter 1   Safety &#62; Safety Precautions &#62; Precautions for Potential Fire Hazards","Use the machine by following the precautions below to protect the machine equipment, plant, and surrounding environment from the danger of fire an...",""],
["./1_4-confirmation-of-machine-st.html","Chapter 1   Safety &#62; Safety Precautions &#62; Confirmation of Machine Status","Machine inspections and maintenance must be performed regularly to maintain optimum machining accuracy and long-term performance, and increase mac...",""],
["./1_5-pre-operation-checks.html","Chapter 1   Safety &#62; Safety Precautions &#62; Pre-operation Checks","Be sure that you fully understand the work procedures and precautions before operating and maintaining the machine. Never operate any machinery if...",""],
["./1_6-implementing-lock-out-and-.html","Chapter 1   Safety &#62; Safety Precautions &#62; Implementing Lock-out and Tag-out","Lock-out consists of shutting down the power source to the machine or devices and locking it.",""],
["./1_7-during-work.html","Chapter 1   Safety &#62; Safety Precautions &#62; During Work","Turn OFF the power before performing maintenance of the machine. When work must be performed with the machine power ON, confirm that all machine o...",""],
["./1_8-handling-of-hazardous-and-.html","Chapter 1   Safety &#62; Safety Precautions &#62; Handling of Hazardous and Toxic Materials","Handlers of hazardous and toxic materials (such as oils and cutting fluid) must receive information, education, and training in accordance with yo...",""],
["./2-warning-labels.html","Chapter 1   Safety &#62; Warning Labels","Warning labels are affixed to machine parts that are potentially hazardous to warn operators about the hazard and its level of danger and ensure t...",""],
["./2000-hours-(8-months)-maintena.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals &#62; 2000 hours (8 Months) Maintenance","Unit Refer to Content of Maintenance Spindle 4.2.2 Replacing the O ring for the Sleeve Hydraulic Unit 8.2 Replacing the Hydraulic Oil  8.3 Cl...",""],
["./2000-hours-(8-months)-maintena_2.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals &#62; 4000 hours (16 Months) Maintenance","Unit Refer to Content of Maintenance Spindle and Feed Axis Cooling Oil Temperature Controller 6.3 Replacing the Lubricant Oil  6.4 Replacing ...",""],
["./2_1-signal-word-definitions.html","Chapter 1   Safety &#62; Warning Labels &#62; Signal Word Definitions","Signal words are divided into four classes based on the degree of expected risk.",""],
["./2_2-using-warning-labels.html","Chapter 1   Safety &#62; Warning Labels &#62; Using Warning Labels","Do not cover up or peel off the warning labels. Confirm that the operators and maintenance personnel are familiar with the language on the labels....",""],
["./2_3-information-contained-in-w.html","Chapter 1   Safety &#62; Warning Labels &#62; Information Contained in Warning Labels","The two types of warning labels are shown below. Labels with warning text and a warning mark Labels with a warning mark only",""],
["./2_3_1-warning-labels-with-warn.html","Chapter 1   Safety &#62; Warning Labels &#62; Information Contained in Warning Labels &#62; Warning Labels with Warning Text","Signal Word Symbol Description DANGER  Entering enclosed spaces during operation can cause serious injury or death. Turn OFF the main power b...",""],
["./2_3_2-warning-labels-with-warn.html","Chapter 1   Safety &#62; Warning Labels &#62; Information Contained in Warning Labels &#62; Warning Labels with Warning Marks Only","Symbol Description  This warning label is affixed to parts where touching the internal high-voltage components may result in electrical shock...",""],
["./2_4-warning-labels-locations.html","Chapter 1   Safety &#62; Warning Labels &#62; Warning Labels Locations","Warning Labels Locations Navigation: Chapter 1 Safety Warning Labels Warning Labels Locations ",""],
["./2_4_1-warning-labels-locations.html","Chapter 1   Safety &#62; Warning Labels &#62; Warning Labels Locations &#62; Warning Labels Locations on Standard Machine","Warning Labels Locations on Standard Machine Navigation: Chapter 1 Safety Warning Labels Warning Labels Locations Warning Labels Locations on Stan...",""],
["./2_4_2-labels.html","Chapter 1   Safety &#62; Warning Labels &#62; Warning Labels Locations &#62; Labels","-NOTES- Locations and types of labels differ depending on the machine type or specifications (the above diagram is an example) and subject to revi...",""],
["./3-safety-devices.html","3 Safety Devices","Safety devices are installed on the machine to protect operators and maintenance personnel. The safety devices also include ones that function on ...",""],
["./3-safety-devices_2.html","Chapter 1   Safety &#62; Safety Devices","DANGER Never disable or remove any safety device.  Safety devices are installed on the machine to protect operators and maintenance personnel...",""],
["./3_1-emergency-stop-switch_2.html","Chapter 1   Safety &#62; Safety Devices &#62; Emergency Stop Switch","WARNING Make sure operators know the locations of all the \"Emergency Stop\" switches prior to performing machine operation or maintenance...",""],
["./3_2-door-switch.html","3.2 Door Switch","The door switch is a device for detecting and controlling the status of doors and covers.",""],
["./3_2-door-switch_2.html","Chapter 1   Safety &#62; Safety Devices &#62; Door Switch","The door switch is a device for detecting and controlling the status of doors and covers.",""],
["./4-work-hazards.html","4 Work Hazards","The following tables list examples of hazardous actions and situations during machine operation and maintenance and examples of the resulting acci...",""],
["./4-work-hazards_2.html","Chapter 1   Safety &#62; Work Hazards","The following tables list examples of hazardous actions and situations during machine operation and maintenance and examples of the resulting acci...",""],
["./4_1-area-surrounding-machine.html","4.1 Area Surrounding Machine","Action/Situation Result Tripping over cables, piping, or change in height Falling Operator working on oily floor Fall, bone fracture, injury Bring...",""],
["./4_1-area-surrounding-machine_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Area Surrounding Machine","Action/Situation Result Tripping over cables, piping, or change in height Falling Operator working on oily floor Fall, bone fracture, injury Bring...",""],
["./4_10-other-peripheral-equipmen.html","4.10 Other Peripheral Equipment","Action/Situation Result Performing operation without turning OFF the machine power Injury or death, electric shock",""],
["./4_10-other-peripheral-equipmen_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Other Peripheral Equipment","Action/Situation Result Performing operation without turning OFF the machine power Injury or death, electric shock",""],
["./4_2-electrical-system.html","4.2 Electrical System","Action/Situation Result Performing inspection or maintenance operation without turning OFF the machine power (Refer to NOTE) Electric shock, break...",""],
["./4_2-electrical-system_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Electrical System","Action/Situation Result Performing inspection or maintenance operation without turning OFF the machine power (Refer to NOTES) Electric shock, brea...",""],
["./4_3-parameters.html","4.3 Parameters","Action/Situation Result Changing NC/machine parameters not listed in manual Injury or death, workpiece damage, breakdown of the machine Forgetting...",""],
["./4_4-inside-the-machining-chamb.html","4.4 Inside the Machining Chamber","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Operator entering machining chamber...",""],
["./4_4-inside-the-machining-chamb_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Inside the Machining Chamber","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Operator entering machining chamber...",""],
["./4_5-tool-magazine.html","4.5 Tool Magazine","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Operator entering the tool magazine...",""],
["./4_5-tool-magazine_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Tool Magazine","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Operator entering the tool magazine...",""],
["./4_6-cutting-fluid-supply-unit_.html","4.6 Cutting Fluid Supply Unit/Chip Disposal Device/Cutting Fluid Temperature Controller/Dust Collector (Graphite Specifications)","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Inserting hands or feet into convey...",""],
["./4_6-cutting-fluid-supply-unit__2.html","Chapter 1   Safety &#62; Work Hazards &#62; Cutting Fluid Supply Unit/Chip Disposal Device/Cutting Fluid Temperature Controller/Dust Collector (Graphite Specifications)","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Inserting hands or feet into convey...",""],
["./4_7-spindle-lubricant-controll.html","4.7 Spindle Lubricant Controller/Feed Axis Temperature Controller/Hydraulic Unit","Action/Situation Result Touching part or component immediately after operation Burns Oil temperature exceeds flash point Flash point of MAKINO SPI...",""],
["./4_7-spindle-lubricant-controll_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Spindle Lubricant Controller/Feed Axis Temperature Controller/Hydraulic Unit","Action/Situation Result Touching part or component immediately after operation Burns Oil temperature exceeds flash point Flash point of MAKINO SPI...",""],
["./4_8-pneumatic-unit.html","4.8 Pneumatic Unit","Action/Situation Result Removing the pneumatic unit source piping on the machine side or disassembling the primary-side line filter without shutti...",""],
["./4_8-pneumatic-unit_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Pneumatic Unit","Action/Situation Result Removing the pneumatic unit source piping on the machine side or disassembling the primary-side line filter without shutti...",""],
["./4_9-splash-guard.html","4.9 Splash Guard","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Operator entering splash guard with...",""],
["./4_9-splash-guard_2.html","Chapter 1   Safety &#62; Work Hazards &#62; Splash Guard","Action/Situation Result Working without performing lock-out and tag-out Injury or death, damage to the machine Operator entering splash guard with...",""],
["./5-occupational-health-and-safe.html","Chapter 1   Safety &#62; Occupational Health and Safety Management","Occupational Health and Safety Management Navigation: Chapter 1 Safety Occupational Health and Safety Management ",""],
["./50-hours-(weekly)-maintenance.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals &#62; 50 hours (Weekly) Maintenance","Unit Refer to Content of Maintenance Tool Magazine 5.1 Checking/Cleaning of Tool Shank  5.2 Checking/Cleaning Tool Pot Key of Tool Magazine S...",""],
["./500-hours-(2-months)-maintenan.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals &#62; 500 hours (2 months) Maintenance","Unit Refer to Content of Maintenance Spindle 4.3 Greasing of Spindle Collet Automatic Grease Supply Unit 7.1 Replacing the Grease Cartridge Chip D...",""],
["./5_1-safety-device-inspection.html","Chapter 1   Safety &#62; Occupational Health and Safety Management &#62; Safety Device Inspection","Perform periodic maintenance and inspection of the safety devices used on this machine in order to ensure that they continue to function normally....",""],
["./5_2-noise.html","Chapter 1   Safety &#62; Occupational Health and Safety Management &#62; Noise","The noise level of the machine is shown below. Noise level: 80 dB maximum (A-weighted sound level) These values are measured values at full operat...",""],
["./5_3-personal-protective-equipm.html","Chapter 1   Safety &#62; Occupational Health and Safety Management &#62; Personal Protective Equipment","When conducting installation, operation, and maintenance work on the machine, be sure to protect your body from the following potential hazards.",""],
["./5_4-disposal-of-waste-products.html","Chapter 1   Safety &#62; Occupational Health and Safety Management &#62; Disposal of Waste Products","Disposal of Waste Products Navigation: Chapter 1 Safety Occupational Health and Safety Management Disposal of Waste Products ",""],
["./5_4_1-disposal-of-waste-oil_-w.html","Chapter 1   Safety &#62; Occupational Health and Safety Management &#62; Disposal of Waste Products &#62; Disposal of Waste Oil, Waste Fluids and Waste Materials","Dispose of liquids such as cutting fluid, grease, hydraulic oil and lubricant, and chips or graphite dust, all of which are discharged during oper...",""],
["./5_4_2-disposal-of-this-machine.html","Chapter 1   Safety &#62; Occupational Health and Safety Management &#62; Disposal of Waste Products &#62; Disposal of This Machine","When disposing of this machine or its parts, disassemble and dispose of them in accordance with the laws, regulations, and ordinances established ...",""],
["./6000-hours-maintenance.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals &#62; 6000 hours (2 Years) Maintenance","Unit Refer to Content of Maintenance Chip Disposal/Cutting Fluid Supply Unit 10.1.2 Replacement of Mesh Filter  10.5.2 Special Cleaning for C...",""],
["./air-dryer.html","Chapter 2   Periodic Maintenance &#62; Air Dryer","Air Dryer Navigation: Chapter 2 Periodic Maintenance Air Dryer ",""],
["./automatic-grease-supply-unit.html","Chapter 2   Periodic Maintenance &#62; Automatic Grease Supply Unit","Automatic Grease Supply Unit Navigation: Chapter 2 Periodic Maintenance Automatic Grease Supply Unit ",""],
["./chapter-2-periodic-maintenance.html","Chapter 2 Periodic Maintenance","Chapter 2 Periodic Maintenance Navigation: No topics above this level Chapter 2 Periodic Maintenance ",""],
["./checking-and-adjusting-the-pre.html","Chapter 2   Periodic Maintenance &#62; Pneumatic System &#62; Checking and Adjusting the Pressure of the Air Regulator","Maintenance period: Every 50 Hours  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to pe...",""],
["./checking-for-clogging-of-the-m.html","Chapter 2   Periodic Maintenance &#62; Pneumatic System &#62; Checking for Clogging of the Mist Separator","Maintenance period: Daily  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to performing ...",""],
["./checking-of-cutting-fluid-leve.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Checking/Replenishment of Cutting Fluid Level &#62; Checking of Cutting Fluid Level","Maintenance period: Daily  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to performing ...",""],
["./checking-of-cyclone-filter-inl.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Checking/Cleaning of Cyclone Filter (Option) &#62; Checking of Cyclone Filter Inlet Pressure","Maintenance period: Daily  WARNING When performing any work, be sure to place a warning tag on each operation panel, main power switch and ot...",""],
["./checking-of-evaporation-thermo.html","Chapter 2   Periodic Maintenance &#62; Air Dryer &#62; Checking of Evaporation Thermometer","Maintenance period: Every 50 Hours  WARNING Wear safety gloves and safety glasses when performing this procedure. Procedure (Refer to Figure ...",""],
["./checking-oil-level-and-refill2.html","Chapter 2   Periodic Maintenance &#62; Hydraulic Unit &#62; Checking Oil Level and Refilling with Oil","Maintenance period: Every 50 Hours  WARNING Wear safety gloves and safety glasses when performing this procedure.   CAUTION Do not perfo...",""],
["./checking-oil-level-and-refilli.html","Chapter 2   Periodic Maintenance &#62; Spindle and Feed Axis Temperature Controller &#62; Checking Oil Level and Refilling with Oil","Maintenance period: Every 50 Hours  WARNING Wear safety gloves and safety glasses when performing this procedure. Required items Name Order N...",""],
["./checking-the-o-ring-of-the-sle.html","Chapter 2   Periodic Maintenance &#62; Spindle &#62; Checking/Replacement of Sleeve Coolant Seal &#62; Checking the O Ring of the Sleeve","Maintenance period: Daily  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to performing ...",""],
["./checking_adjusting-the-levelin.html","Chapter 2   Periodic Maintenance &#62; Machine &#62; Checking/Adjusting the Leveling of the Machine","Maintenance period: Every 1000 Hours  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to ...",""],
["./checking_cleaning-of-cyclone-f.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Checking/Cleaning of Cyclone Filter (Option)","The cyclone filter unit is an option.",""],
["./checking_cleaning-of-tool-maga.html","Chapter 2   Periodic Maintenance &#62; Tool Magazine &#62; Checking/Cleaning Tool Pot Key of Tool Magazine","Maintenance period: Every 50 Hours  WARNING Exercise extreme caution as entry into the machine is necessary in order to perform the following...",""],
["./checking_cleaning-of-tool-shan.html","Chapter 2   Periodic Maintenance &#62; Tool Magazine &#62; Checking/Cleaning of Tool Shank","Maintenance period: Every 50 Hours  WARNING Exercise extreme caution as entry into the machine is necessary in order to perform the following...",""],
["./checking_replenishment-of-cutt.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Checking/Replenishment of Cutting Fluid Level","Checking/Replenishment of Cutting Fluid Level Navigation: Chapter 2 Periodic Maintenance Chip Disposal/Cutting Fluid Supply Unit Checking/Replenis...",""],
["./chip-disposal_cutting-fluid-s2.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Chip Disposal (Standard)","Chip disposal is done manually or automatically. Automatic chip disposal uses the optional lift-up chip conveyor (LUCC).",""],
["./chip-disposal_cutting-fluid-su.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit","Specification Measurement (Litres) Coolant Tank (Total volume available for filling) 750",""],
["./cleaning-of-coolant-pumps.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Cleaning of Coolant Pumps","Maintenance period: Every 500 Hours Procedure (Refer to Figure 10.6) With chip tray usage and finer chip applications, there is the possibility th...",""],
["./cleaning-of-coolant-tank.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Cleaning of Coolant Tank","Make sure to clean the machining chamber before performing this work.",""],
["./cleaning-of-coolant-tank2.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Cleaning of Coolant Tank &#62; Cleaning of Coolant Clean Tank","Maintenance period: Every 2000 Hours Procedure (Refer to Figure 10.5) Turn OFF the power supply. Open all maintenance covers [1] and the fill port...",""],
["./cleaning-of-cutting-fluid-temp.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Cleaning of Cutting Fluid Temperature Controller Air Filter and Condenser (Option)","The cutting fluid temperature controller is an option.",""],
["./cleaning-of-cutting-fluid-temp_2.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Cleaning of Cutting Fluid Temperature Controller Air Filter and Condenser (Option) &#62; Cleaning of Cutting Fluid Temperature Controller Air Filter and Condenser","Maintenance period: Every 50 hours  WARNING Turn OFF the power before performing the following procedures. When performing any work, be sure ...",""],
["./cleaning-of-cyclone-filter-buc.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Checking/Cleaning of Cyclone Filter (Option) &#62; Cleaning of Cyclone Filter Bucket","Maintenance period: Every 1000 Hours  WARNING Turn OFF the power before performing the following procedures. When performing any work, be sur...",""],
["./cleaning-of-ventilation-grill.html","Chapter 2   Periodic Maintenance &#62; Air Dryer &#62; Cleaning of Ventilation Grill","Maintenance period: Every 500 Hours  WARNING Be sure to turn OFF the power supply and confirm that the Air Dryer has completely stopped befor...",""],
["./cleaning-the-air-filter-and-th.html","Chapter 2   Periodic Maintenance &#62; Spindle and Feed Axis Temperature Controller &#62; Cleaning the Air Filter and the Condenser","Maintenance period: Every 50 Hours  WARNING Be sure to turn OFF the power supply and confirm that the spindle lubricant temperature controlle...",""],
["./cleaning-the-filter-for-the-co.html","Chapter 2   Periodic Maintenance &#62; Machine Controller &#62; Cleaning the Filter for the Cooling Fan","Maintenance period: Every 500 Hours The filter is located on the top right side of the Machine Tool Cabinet (MTC). Procedure (Refer to Figure 12.1...",""],
["./cleaning-the-hydraulic-unit-fi.html","Chapter 2   Periodic Maintenance &#62; Hydraulic Unit &#62; Cleaning the Hydraulic Unit Filter Element","Maintenance period: Every 2000 Hours  WARNING Make sure to turn OFF the power supply and confirm that the hydraulic unit has completely stopp...",""],
["./cleaning-the-spindle-taper-sec.html","Chapter 2   Periodic Maintenance &#62; Spindle &#62; Cleaning the Spindle Taper Section","Maintenance period: Daily  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to performing ...",""],
["./cleaning_replacement-of-auto-d.html","Chapter 2   Periodic Maintenance &#62; Air Dryer &#62; Cleaning/Replacement of Auto Drain Strainer","Maintenance period: Every 500 Hours  WARNING Be sure to turn OFF the power supply and confirm that the Air Dryer has completely stopped perfo...",""],
["./daily_pre-operation-inspection.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Daily/Pre-Operation Inspection/Maintenance","NOTICE Be sure to always conduct the daily or pre-operation inspection before using the machine.  Figure 2.1 Daily or Pre-operation Inspectio...",""],
["./emergency-stop-switch.html","\"Emergency Stop\" Switch","WARNING Make sure operators know the locations of all the \"Emergency Stop\" switches prior to performing machine operation or maintenance...",""],
["./general-contents.html","General Contents","Chap. 1   Safety This chapter describes the safety devices and warning labels, work and operating precautions, and other information for ensu...",""],
["./greasing-of-spindle-collet.html","Chapter 2   Periodic Maintenance &#62; Spindle &#62; Greasing of Spindle Collet","Maintenance period: Every 500 Hours  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to p...",""],
["./hydraulic-unit.html","Chapter 2   Periodic Maintenance &#62; Hydraulic Unit","Hydraulic Unit Navigation: Chapter 2 Periodic Maintenance Hydraulic Unit ",""],
["./important-information-2_2.html","Important Information 2/2","Important points for work safety Familiarize yourself with the safety precautions and functions before attempting to operate, maintain, or inspect...",""],
["./important-information.html","Important Information","General Do not attempt to modify the machine. Operation, maintenance, and inspection of this machine must be performed by staffs who have received...",""],
["./inspecting_replacing-the-o-rin.html","Chapter 2   Periodic Maintenance &#62; Spindle &#62; Checking/Replacement of Sleeve Coolant Seal","The O ring of the sleeve needs to be inspected and replaced only for models that use through-spindle coolant.",""],
["./introduction.html","Introduction","This machine is an NC machine tool (machining center) that incorporates an automatic tool change function and performs a wide range of machining o...",""],
["./machine-controller.html","Chapter 2   Periodic Maintenance &#62; Machine Controller","Machine Controller Navigation: Chapter 2 Periodic Maintenance Machine Controller ",""],
["./machine.html","Chapter 2   Periodic Maintenance &#62; Machine","Machine Navigation: Chapter 2 Periodic Maintenance Machine ",""],
["./maintenance-based-on-machine-r.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Maintenance Based on Machine Running Time Intervals","The following sections lists the maintenance content required every time a specified machine running time interval has elapsed.",""],
["./manual-chip-disposal-from-chip.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Chip Disposal (Standard) &#62; Manual Chip Disposal from Chip Bucket","Maintenance period: Daily  Procedure (Refer to Figure 10.1) Using the scraper [2], clear chip from the chip bucket [1]. This completes the ma...",""],
["./manuals-and-how-to-use-them-2_.html","Manuals and How to Use Them 2/2","Notation used in this manual  DANGER Indicates an imminent hazard which, if not avoided, will result in death or serious injury.  WARNIN...",""],
["./manuals-and-how-to-use-them.html","Manuals and How to Use Them","Manuals belonging to this machine. Name  Description Instruction Manual This manual includes the basic information (overview, specifications)...",""],
["./periodic-maintenance-list.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List","Periodic Maintenance List Navigation: Chapter 2 Periodic Maintenance Periodic Maintenance List ",""],
["./pneumatic-system.html","Chapter 2   Periodic Maintenance &#62; Pneumatic System","Pneumatic System Navigation: Chapter 2 Periodic Maintenance Pneumatic System ",""],
["./prior-to-performing-operation.html","Chapter 2   Periodic Maintenance &#62; Prior to Performing Operation","WARNING Read Chap. 1 thoroughly and ensure adequate precautions are taken before performing inspections and maintenance. When performing any work,...",""],
["./replacement-of-air-filter.html","Chapter 2   Periodic Maintenance &#62; Air Dryer &#62; Replacement of Air Filter","Maintenance period: Every 2000 Hours  WARNING Be sure to turn OFF the power supply and confirm that the Air Dryer has completely stopped perf...",""],
["./replacement-of-mesh-filter.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Chip Disposal (Standard) &#62; Replacement of Mesh Filter","Maintenance period: Every 6000 Hours  Procedure (Refer to Figure 10.1) Check mesh filter [3] for damage. If damaged, contact Makino service r...",""],
["./replacement-of-pump-mechancial.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Replacement of Pump Mechanical Seal Kit","The pumps below have mechanical seals that need to be periodically replaced. (Refer to Replacement Parts)",""],
["./replacement-of-spindle-rotary-.html","Chapter 2   Periodic Maintenance &#62; Spindle &#62; Replacement of Spindle Rotary Union","Maintenance period: Every 20000 Hours/ When Damage Noted)",""],
["./replacing-the-absolute-pulse-c.html","Chapter 2   Periodic Maintenance &#62; Machine Controller &#62; Replacing the Absolute Pulse Coder/Scale Batteries","Maintenance period: Every 6000 Hours  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to ...",""],
["./replacing-the-exhaust-cleaner-.html","Chapter 2   Periodic Maintenance &#62; Spindle and Feed Axis Temperature Controller &#62; Replacing the Exhaust Cleaner Element (20K)","Maintenance period: Every 4000 Hours  WARNING Be sure to turn OFF the power supply and confirm that the lubricant unit has completely stopped...",""],
["./replacing-the-grease-cartridge.html","Chapter 2   Periodic Maintenance &#62; Automatic Grease Supply Unit &#62; Replacing the Grease Cartridge","Maintenance period: Every 500 Hours  WARNING Turn OFF the power supply before performing the following procedures. Wear safety gloves and saf...",""],
["./replacing-the-hydraulic-oil.html","Chapter 2   Periodic Maintenance &#62; Hydraulic Unit &#62; Replacing the Hydraulic Oil","Maintenance period: Every 2000 Hours  WARNING Make sure to turn OFF the power supply and confirm that the hydraulic unit has completely stopp...",""],
["./replacing-the-line-filter-elem.html","Chapter 2   Periodic Maintenance &#62; Spindle and Feed Axis Temperature Controller &#62; Replacing the Line Filter Element (20K)","Maintenance period: Every 4000 Hours  WARNING Be sure to turn OFF the power supply and confirm that the lubricant unit has completely stopped...",""],
["./replacing-the-lubricant-oil.html","Chapter 2   Periodic Maintenance &#62; Spindle and Feed Axis Temperature Controller &#62; Replacing the Lubricant Oil","Maintenance period: Every 4000 Hours  WARNING Be sure to turn OFF the power supply and confirm that the lubricant unit has completely stopped...",""],
["./replacing-the-main-air-unit-fi.html","Chapter 2   Periodic Maintenance &#62; Pneumatic System &#62; Replacing the Main Air Unit Filter","Maintenance period: Every 2000 Hours  WARNING Turn OFF the power supply before performing the following procedures. Do not remove the bowl wh...",""],
["./replacing-the-mist-separator-e.html","Chapter 2   Periodic Maintenance &#62; Pneumatic System &#62; Replacing the Mist Separator Filter ","Maintenance period: Every 2000 Hours  WARNING Turn OFF the machine power supply before performing the following procedures. Do not remove the...",""],
["./replacing-the-nc-backup-batter.html","Chapter 2   Periodic Maintenance &#62; Machine Controller &#62; Replacing the NC Backup Battery","Maintenance period: Every 6000 Hours  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to ...",""],
["./replacing-the-o-ring-for-the-s.html","Chapter 2   Periodic Maintenance &#62; Spindle &#62; Checking/Replacement of Sleeve Coolant Seal &#62; Replacing the O Ring for the Sleeve","Maintenance period: Every 2000 Hours  WARNING Turn ON the machine power supply, and confirm that all machine movements have stopped prior to ...",""],
["./replenishment-of-cutting-fluid.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Checking/Replenishment of Cutting Fluid Level &#62; Replenishment of Cutting Fluid","Maintenance period: When necessary  WARNING When performing any work, be sure to place a warning tag on each operation panel, main power swit...",""],
["./revision-history.html","Revision History","Manual Title F8 F9 PERIODIC MAINTENANCE MANUAL Professional 6 Manual No. V2831-M2E-XA  No. Manual No. (Month/Year Issued) Contents Remarks 1 ...",""],
["./safety.html","Chapter 1 Safety","Chapter 1 Safety Navigation: No topics above this level Chapter 1 Safety ",""],
["./special-cleaning-for-coolant-t.html","Chapter 2   Periodic Maintenance &#62; Chip Disposal/Cutting Fluid Supply Unit &#62; Cleaning of Coolant Tank &#62; Special Cleaning for Coolant Tank","Maintenance period: Every 6000 Hours Procedure (Refer to Figure 10.5) Turn OFF the power supply. Pull out the coolant tank while being careful tha...",""],
["./spindle-lubrication-temperatur.html","Chapter 2   Periodic Maintenance &#62; Spindle and Feed Axis Temperature Controller","Spindle and Feed Axis Temperature Controller Navigation: Chapter 2 Periodic Maintenance Spindle and Feed Axis Temperature Controller ",""],
["./spindle.html","Chapter 2   Periodic Maintenance &#62; Spindle","Spindle Navigation: Chapter 2 Periodic Maintenance Spindle ",""],
["./tool-magazine.html","Chapter 2   Periodic Maintenance &#62; Tool Magazine","Tool Magazine Navigation: Chapter 2 Periodic Maintenance Tool Magazine ",""],
["./topics_non-toc.html","Topics/Non-TOC","Enter topic text here.",""],
["./warranty-and-disclaimer.html","Warranty and Disclaimer","The information contained in the purchase agreement exchanged with the customer serves as the warranty with Makino.",""],
["./work-after-shutdown.html","Chapter 2   Periodic Maintenance &#62; Periodic Maintenance List &#62; Work After Shutdown","WARNING Turn OFF the power supply before performing the following procedures. Exercise extreme caution as entry into the machine is necessary in o...",""]];
